/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import Dao.DonHangDao;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class DonHang extends javax.swing.JPanel {

    /**
     * Creates new form DonHang
     */
    DonHangDao handleDonHang = new DonHangDao();
    public DonHang() {
        initComponents();
        hienThiDonHang();
        
        tbl_DonHang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tbl_DonHang.getSelectedRow();
                if (selectedRow >= 0) {
                    String selectedOrderId = tbl_DonHang.getValueAt(selectedRow, 0).toString();
                    hienThiChiTietDonHang(selectedOrderId);
                }
            }
        }
    });
    }

    private void hienThiDonHang() {
    List<Pojo.DonHang> dsDonHang = handleDonHang.getAllOrders();
    DefaultTableModel dtm = new DefaultTableModel();
    
    // Thêm các cột cho bảng đơn hàng
    dtm.addColumn("Mã đơn hàng");
    dtm.addColumn("Mã khách hàng");
    dtm.addColumn("Ngày đặt hàng");
    dtm.addColumn("Tổng tiền");
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    for (Pojo.DonHang donHang : dsDonHang) {
        dtm.addRow(new Object[]{
            donHang.getId(),
            donHang.getCustomerID(),
            dateFormat.format(donHang.getOrderDate()),
            donHang.getTotalAmount()
        });
    }
    
    // Thiết lập model cho bảng đơn hàng
    tbl_DonHang.setModel(dtm);
}

private void hienThiChiTietDonHang(String orderId) {
    Pojo.DonHang donHang = handleDonHang.getOrderById(orderId); // Lấy thông tin chi tiết đơn hàng

    DefaultTableModel dtmChiTiet = new DefaultTableModel();
    dtmChiTiet.addColumn("Mã sản phẩm");
    dtmChiTiet.addColumn("Số lượng");
    dtmChiTiet.addColumn("Giá");
    dtmChiTiet.addColumn("Mã khuyến mãi");
    dtmChiTiet.addColumn("Giá khuyến mãi");
    dtmChiTiet.addColumn("Thành tiền"); // Thêm cột Thành tiền
    
    if (donHang != null && donHang.getProducts() != null) {
        for (Pojo.DonHang.Product product : donHang.getProducts()) {
            double thanhTien = product.getQuantity() * product.getPrice(); // Tính Thành tiền
            dtmChiTiet.addRow(new Object[]{
                product.getProductID(),
                product.getQuantity(),
                product.getPrice(),
                product.getPromotionID(),
                product.getDiscountedPrice(),
                thanhTien // Thêm Thành tiền vào bảng
            });
        }
    }
    
    // Thiết lập model cho bảng chi tiết đơn hàng
    tbl_ChiTietDonHang.setModel(dtmChiTiet);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DonHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ChiTietDonHang = new javax.swing.JTable();

        jLabel1.setText("Đơn hàng");

        tbl_DonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_DonHang);

        tbl_ChiTietDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Số lượng", "Giá", "Mã khuyến mãi", "Giá khuyến mãi", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tbl_ChiTietDonHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(432, 432, 432))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_ChiTietDonHang;
    private javax.swing.JTable tbl_DonHang;
    // End of variables declaration//GEN-END:variables
}
