/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author 84862
 */
public class FormTrangChu extends javax.swing.JPanel {

    /**
     * Creates new form FormTrangChu
     */
    public FormTrangChu() {
        initComponents();
      image_TrangChu.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                image();
            }
        });
    }
    public void image() {
        String imagePath = "src\\Anh\\DaiDien.png";

        // Tạo ImageIcon từ hình ảnh
        ImageIcon originalIcon = new ImageIcon(imagePath);

        // Lấy kích thước của JLabel
        int labelWidth = image_TrangChu.getWidth();
        int labelHeight = image_TrangChu.getHeight();

        if (labelWidth > 0 && labelHeight > 0) {
            // Chỉnh sửa kích thước hình ảnh để lấp đầy JLabel
            Image scaledImage = originalIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            image_TrangChu.setIcon(scaledIcon);
        }
    }

//    public void image()
//    {
//        String imagePath = "C:\\AppKhieuNai\\src\\Anh\\DaiDien.png";
//
//        // Tạo ImageIcon từ hình ảnh
//        ImageIcon originalIcon = new ImageIcon(imagePath);
//
//        // Lấy kích thước của JLabel
//        int labelWidth = image_TrangChu.getWidth();
//        int labelHeight = image_TrangChu.getHeight();
//
//        // Chỉnh sửa kích thước hình ảnh để lấp đầy JLabel
//        Image scaledImage = originalIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
//        ImageIcon scaledIcon = new ImageIcon(scaledImage);
//        image_TrangChu.setIcon(scaledIcon);
//     
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_TrangChu = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1370, 700));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image_TrangChu.setPreferredSize(new java.awt.Dimension(1370, 700));
        add(image_TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image_TrangChu;
    // End of variables declaration//GEN-END:variables
}
