/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import Dao.KhachHangDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84862
 */
public class FrmKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form FrmKhachHang
     */
    KhachHangDao handleKhachHang = new KhachHangDao();
    public FrmKhachHang() {
        initComponents();
        hienThi();
        List<String> dsKhachHang = handleKhachHang.getAllCustomerTiers();
        for(String loaiKH:dsKhachHang)
        {
            CB_LoaiKH.addItem(loaiKH);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Email = new javax.swing.JTextField();
        txt_Ma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KhachHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Ten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Upadte = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        CB_LoaiKH = new javax.swing.JComboBox<>();
        txt_SoVour = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1370, 700));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 360, -1));
        add(txt_Ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 360, -1));

        tbl_KhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_KhachHang.setToolTipText("");
        tbl_KhachHang.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_KhachHang.setRowHeight(40);
        tbl_KhachHang.setSelectionBackground(new java.awt.Color(0, 51, 204));
        tbl_KhachHang.setShowGrid(false);
        tbl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KhachHang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1370, 410));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Tên khách hàng:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Mã khách hàng:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Email:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("KHÁCH HÀNG");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));
        add(txt_Ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 360, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Số voucher:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Loại khách hàng:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        btn_Upadte.setBackground(new java.awt.Color(0, 255, 255));
        btn_Upadte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Upadte.setForeground(new java.awt.Color(255, 255, 255));
        btn_Upadte.setText("Sửa");
        btn_Upadte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpadteActionPerformed(evt);
            }
        });
        add(btn_Upadte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 51));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        btn_Them.setBackground(new java.awt.Color(0, 255, 0));
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        btn_LamMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/reset_1.png"))); // NOI18N
        btn_LamMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_LamMoiKeyPressed(evt);
            }
        });
        add(btn_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 80, -1));

        add(CB_LoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 450, -1));
        add(txt_SoVour, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 450, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Tìm kiếm:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));
        add(txt_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 340, -1));

        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });
        add(btn_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

     private void hienThi()
    {
        
        List<Pojo.KhachHang> ds = handleKhachHang.getAllCustomers();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã khách hàng");
        dtm.addColumn("Tên khách hàng");
        dtm.addColumn("Email");
        dtm.addColumn("Loại khách hàng");
        dtm.addColumn("Số vourcher");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dtm.setNumRows(ds.size());
        for(int i=0;i<ds.size();i++)
        {
            Pojo.KhachHang ls = ds.get(i);
            dtm.setValueAt(ls.getId(), i, 0);
            dtm.setValueAt(ls.getCustomerName(),i, 1);
            dtm.setValueAt(ls.getEmail(), i, 2);
            dtm.setValueAt(ls.getTier(), i, 3);
            dtm.setValueAt(ls.getVoucherQuantity(), i, 4);
        }
        tbl_KhachHang.setModel(dtm);
    }
    
    private void tbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachHangMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_KhachHang.getSelectedRow();
        if(selectedRow != -1)
        {
            String ma = tbl_KhachHang.getValueAt(selectedRow, 0).toString();
            String ten = tbl_KhachHang.getValueAt(selectedRow, 1).toString();
            String email = tbl_KhachHang.getValueAt(selectedRow, 2).toString();
            String loaiKH = tbl_KhachHang.getValueAt(selectedRow, 3).toString();
            String soVoucher = tbl_KhachHang.getValueAt(selectedRow, 4).toString();
            txt_Ma.setText(ma);
            txt_Ten.setText(ten);
            txt_Email.setText(email);
            txt_SoVour.setText(soVoucher);
            CB_LoaiKH.setSelectedItem(loaiKH);
        }
    }//GEN-LAST:event_tbl_KhachHangMouseClicked

    private void btn_UpadteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpadteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_KhachHang.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng cần sửa.");
            return;
        }

        // Lấy dữ liệu từ các trường nhập liệu
        String ma = txt_Ma.getText();
        String ten= txt_Ten.getText();
        String email = txt_Email.getText();
        String soVourcher = txt_SoVour.getText();
        String loaiKH = (String) CB_LoaiKH.getSelectedItem();
        // Chuyển đổi ngày sinh từ String sang Date

        int voucherQuantity;
        try {
            voucherQuantity = Integer.parseInt(soVourcher);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số lượng voucher phải là số hợp lệ!");
            return;
        }
        Pojo.KhachHang kh = new Pojo.KhachHang();
        kh.setId(ma);
        kh.setCustomerName(ten);
        kh.setEmail(email);
        kh.setTier(loaiKH);
        kh.setVoucherQuantity(voucherQuantity);

        // Gọi hàm SuaNguoiKhieuNai để cập nhật vào cơ sở dữ liệu
        boolean success = handleKhachHang.updateCustomer(kh);

        // Thông báo kết quả và cập nhật bảng
        if (success) {
            JOptionPane.showMessageDialog(null, "Sửa khách hàng thành công!");
            hienThi();
        } else {
            JOptionPane.showMessageDialog(null, "Sửa khách hàng thất bại!");
        }
    }//GEN-LAST:event_btn_UpadteActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        //TODO add your handling code here:
        int selectedRow = tbl_KhachHang.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng cần xóa.");
            return;
        }

        // Lấy mã khách hàng từ hàng được chọn
        String ma = tbl_KhachHang.getValueAt(selectedRow, 0).toString();

        // Hiển thị hộp thoại xác nhận
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa khách hàng này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

        // Nếu người dùng chọn "Có"
        if (confirm == JOptionPane.YES_OPTION) {
            // Gọi hàm xóa để xóa khỏi cơ sở dữ liệu
            boolean success = handleKhachHang.deleteCustomer(ma);

            // Thông báo kết quả và cập nhật bảng
            if (success) {
                JOptionPane.showMessageDialog(null, "Xóa khách hàng thành công!");
                hienThi();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa khách hàng thất bại!");
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        String ma = txt_Ma.getText();
        String ten= txt_Ten.getText();
        String email = txt_Email.getText();
        String soVourcher = txt_SoVour.getText();
        String loaiKH = (String) CB_LoaiKH.getSelectedItem();
        // Chuyển đổi ngày sinh từ String sang Date

        int voucherQuantity;
        try {
            voucherQuantity = Integer.parseInt(soVourcher);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số lượng voucher phải là số hợp lệ!");
            return;
        }
        List<String> promotionIDs = new ArrayList<>();

        Pojo.KhachHang kh = new Pojo.KhachHang();
        kh.setId(ma);
        kh.setCustomerName(ten);
        kh.setEmail(email);
        kh.setTier(loaiKH);
        kh.setVoucherQuantity(voucherQuantity);

        // Gọi hàm themNguoiKhieuNai để thêm vào cơ sở dữ liệu
        boolean success = handleKhachHang.addCustomer(kh);

        // Thông báo kết quả
        if (success) {
            JOptionPane.showMessageDialog(null, "Thêm khách hàng thành công!");
            hienThi();
        } else {
            JOptionPane.showMessageDialog(null, "Thêm khách hàng thất bại do trùng Mã khách hàng!");
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        String searchText = txt_TimKiem.getText();

        // Gọi phương thức getCustomersByName với tên cần tìm
        List<Pojo.KhachHang> ds = handleKhachHang.getCustomersByName(searchText);

        // Tạo mô hình bảng mới để hiển thị kết quả
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã khách hàng");
        dtm.addColumn("Tên khách hàng");
        dtm.addColumn("Email");
        dtm.addColumn("Loại khách hàng");
        dtm.addColumn("Số vourcher");

        // Cập nhật số lượng dòng trong mô hình bảng
        dtm.setNumRows(ds.size());

        // Duyệt qua danh sách khách hàng và thêm vào bảng
        for (int i = 0; i < ds.size(); i++) {
            Pojo.KhachHang kh = ds.get(i);
            dtm.setValueAt(kh.getId(), i, 0);
            dtm.setValueAt(kh.getCustomerName(), i, 1);
            dtm.setValueAt(kh.getEmail(), i, 2);
            dtm.setValueAt(kh.getTier(), i, 3);
            dtm.setValueAt(kh.getVoucherQuantity(), i, 4);
        }

        // Gán mô hình bảng mới vào bảng tbl_KhachHang
        tbl_KhachHang.setModel(dtm);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_LamMoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_LamMoiKeyPressed
        // TODO add your handling code here:
        txt_Ma.setText("");
        txt_Ten.setText("");
        txt_Email.setText("");
        txt_SoVour.setText("");
    }//GEN-LAST:event_btn_LamMoiKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_LoaiKH;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Upadte;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_KhachHang;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Ma;
    private javax.swing.JTextField txt_SoVour;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
