/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import Dao.NhanVienDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUU KHANH
 */
public class NhanVien extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien
     */
    NhanVienDao handleEmployee = new NhanVienDao();
    public NhanVien() {
        initComponents();
        hienThi();
    }
    
    private void hienThi(){
    List<String> listPosition = handleEmployee.getEmployeePosition();
    cbx_position.removeAllItems();
    cbx_gender.removeAllItems();
    for (String position : listPosition) {
        cbx_position.addItem(position);
    }

    List<String> listGender = handleEmployee.getEmployeeGender();
    for (String gender : listGender) {
        cbx_gender.addItem(gender);
    }

    List<Pojo.NhanVien> ds = handleEmployee.getAllEmployees();
    DefaultTableModel dtm = new DefaultTableModel();
    dtm.addColumn("Mã nhân viên");
    dtm.addColumn("Tên nhân viên");
    dtm.addColumn("Vị trí");
    dtm.addColumn("SĐT");
    dtm.addColumn("Giới tính");
    dtm.addColumn("Ngày sinh");
    dtm.setNumRows(ds.size());
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    for(int i=0;i<ds.size();i++)
        {
            Pojo.NhanVien ls = ds.get(i);
            dtm.setValueAt(ls.getId(), i, 0);
            dtm.setValueAt(ls.getNameEmployee(),i, 1);
            dtm.setValueAt(ls.getPosition(), i, 2);
            dtm.setValueAt(ls.getPhone(), i, 3);
            dtm.setValueAt(ls.getGender(), i, 4);
            dtm.setValueAt((ls.getBod() != null) ? dateFormat.format(ls.getBod()) : "", i, 5);
        }
    tbl_Employee.setModel(dtm);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_idEmployee = new javax.swing.JTextField();
        txt_nameEmployee = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        cbx_position = new javax.swing.JComboBox<>();
        cbx_gender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Employee = new javax.swing.JTable();
        btn_Add = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        txt_bod = new javax.swing.JFormattedTextField();

        setMinimumSize(new java.awt.Dimension(1370, 700));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nhân viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Mã nhân viên:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Tên nhân viên:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Số điện thoại:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Giới tính:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Chức vụ:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Ngày sinh:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));
        add(txt_idEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 230, -1));
        add(txt_nameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 230, -1));
        add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 220, -1));

        add(cbx_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, -1));

        add(cbx_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 140, -1));

        tbl_Employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Employee.setRowHeight(40);
        tbl_Employee.setSelectionBackground(new java.awt.Color(51, 51, 255));
        tbl_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_EmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Employee);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 1060, 250));

        btn_Add.setBackground(new java.awt.Color(102, 255, 51));
        btn_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Thêm");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        btn_Delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Xóa");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        btn_Update.setBackground(new java.awt.Color(0, 255, 204));
        btn_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Sửa");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        btn_Clear.setBackground(new java.awt.Color(51, 153, 255));
        btn_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clear.setText("Làm mới");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        txt_bod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        add(txt_bod, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        String id = txt_idEmployee.getText().trim();
        String name = txt_nameEmployee.getText().trim();
        String position = (String) cbx_position.getSelectedItem();
        String phone = txt_phone.getText().trim();
        String gender = (String) cbx_gender.getSelectedItem();
        String bod = txt_bod.getText().trim();

        if (id.isEmpty() || name.isEmpty() || phone.isEmpty() || bod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin.");
            return;
        }

        Pojo.NhanVien employee = new Pojo.NhanVien();
        employee.setId(id);
        employee.setNameEmployee(name);
        employee.setPosition(position);
        employee.setPhone(phone);
        employee.setGender(gender);

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false); // Đặt chế độ kiểm tra nghiêm ngặt
        try {
            Date birthDate = dateFormat.parse(bod);
            employee.setBod(birthDate);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ. Vui lòng nhập lại theo định dạng yyyy-MM-dd.");
            return;
        }

        boolean success = handleEmployee.addEmployee(employee);

        if (success) {
            JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công!");
            hienThi(); // Cập nhật lại bảng hoặc giao diện
        } else {
            JOptionPane.showMessageDialog(null, "Thêm nhân viên thất bại!");
        }
    }//GEN-LAST:event_btn_AddActionPerformed

    private void tbl_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_EmployeeMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_Employee.getSelectedRow();
        if (selectedRow != -1) {
            String id = tbl_Employee.getValueAt(selectedRow, 0).toString();
            String name = tbl_Employee.getValueAt(selectedRow, 1).toString();
            String position = tbl_Employee.getValueAt(selectedRow, 2).toString();
            String phone = tbl_Employee.getValueAt(selectedRow, 3).toString();
            String gender = tbl_Employee.getValueAt(selectedRow, 4).toString();
            String bodString = tbl_Employee.getValueAt(selectedRow, 5).toString();

            txt_idEmployee.setText(id);
            txt_nameEmployee.setText(name);
            cbx_position.setSelectedItem(position);
            txt_phone.setText(phone);
            cbx_gender.setSelectedItem(gender);

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date bod = dateFormat.parse(bodString);
                System.out.println("BOD: " + bod);
                txt_bod.setValue(bod); 
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
                e.printStackTrace(); 
            }
        }
    }//GEN-LAST:event_tbl_EmployeeMouseClicked

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_Employee.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên cần xóa.");
            return;
        }

        String id = tbl_Employee.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa nhân viên này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = handleEmployee.deleteEmployee(id);
            JOptionPane.showMessageDialog(null, success ? "Xóa nhân viên thành công!" : "Xóa nhân viên thất bại!");
            if (success) {
                hienThi();
            }
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_Employee.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên cần sửa.");
            return;
        }

        String id = txt_idEmployee.getText().trim();
        String name = txt_nameEmployee.getText().trim();
        String position = (String) cbx_position.getSelectedItem();
        String phone = txt_phone.getText().trim();
        String gender = (String) cbx_gender.getSelectedItem();

        Date bod;
        try {
            bod = (Date) txt_bod.getValue();
            if (bod == null) {
                JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
                return;
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
            return;
        }

        // Tạo đối tượng NhanVien
        Pojo.NhanVien employee = new Pojo.NhanVien(id, name, position, phone, gender, bod);

        // Gọi hàm updateEmployee để cập nhật vào cơ sở dữ liệu
        boolean success = handleEmployee.updateEmployee(employee);
        // Thông báo kết quả
        JOptionPane.showMessageDialog(null, success ? "Sửa thông tin nhân viên thành công!" : "Sửa thông tin nhân viên thất bại!");
        if (success) {
            hienThi(); // Cập nhật bảng
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        txt_idEmployee.setText("");
        txt_nameEmployee.setText(""); 
        txt_phone.setText(""); 
        txt_bod.setValue(null); 
        cbx_position.setSelectedIndex(-1); 
        cbx_gender.setSelectedIndex(-1);
    }//GEN-LAST:event_btn_ClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> cbx_gender;
    private javax.swing.JComboBox<String> cbx_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Employee;
    private javax.swing.JFormattedTextField txt_bod;
    private javax.swing.JTextField txt_idEmployee;
    private javax.swing.JTextField txt_nameEmployee;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
